#!/usr/bin/env bash
#
# Recursively calls all setup.sh scripts in the subdirectories
#  of this directory.
#

info() {
  printf "\033[0;34m$1\033[0m"
}

success() {
  printf "\033[0;32m$1\033[0m"
}

error() {
  printf "\033[1;31m$1\033[0m"
}

run_setup_script() {
  script="$1"

  info "Running setup $script...\n"
  if sh "$script"; then
    success "[SUCCESS] $1\n"
  else
    error "[ERROR] $1\n\n"
  fi
}

# Find all setup.sh scripts and run them
for script in $(find . -name 'setup.sh'); do
  run_setup_script "$script"
done
