#!/usr/bin/env bash

dock_add() {
  if [ -d "$1" ]; then
    dockutil --add "$1"
  fi
}

echo "> Installing dockutil..."
brew install dockutil

echo "> Removing all dock items..."
dockutil --remove all

echo "> Adding new items..."
dock_add "/Applications/Brave Browser.app"
dock_add /Applications/iTerm.app
dock_add "/Applications/IntelliJ IDEA CE.app"
dock_add /Applications/KeePassXC.app
dock_add /Applications/Mailspring.app
dock_add "/Applications/Sublime Text.app"
dock_add /Applications/Fork.app
dock_add /Applications

echo "> Manual actions"
cat <<EOD
1. Turn hiding on (cmd + alt + D)
2. Rightclick dock > Dock preferences
  a. Change _Position on screen_ to _Left_
  b. Uncheck _show recent applications in Dock_
EOD

