#!/usr/bin/env bash

brew tap immortaleeb/tap
brew tap heroku/brew

# core tools
brew install \
  git \
  coreutils \
  watch

# other tools
brew install \
  tmux \
  ag \
  gradle \
  lnav \
  bashmarks \
  awscli \
  jq \
  pyenv \
  tmuxp \
  asdf \
  heroku

