#!/usr/bin/env bash

# General
brew install --cask \
  brave-browser \
  rectangle \
  flux \
  flycut \
  karabiner-elements \
  android-file-transfer \
  flameshot \
  the-unarchiver

# Office Tools
brew install --cask \
  joplin \
  syncthing
# brew install --cask mailspring
# brew install --cask libreoffice

# Dev Tools
brew install --cask \
  docker \
  iterm2 \
  sublime-text \
  fork \
  postman \
  meld
# brew install --cask intellij-idea-ce
# brew install --cask tunnelblick
# brew install --cask yed

# Secrets
brew install --cask keepassxc

# Multimedia
brew install --cask \
  spotify \
  vlc

