#!/usr/bin/env bash

brew tap immortaleeb/tap
brew tap heroku/brew

brew install \
  git \
  coreutils \
  tmux \
  ag \
  gradle \
  lnav \
  bashmarks \
  awscli \
  jq \
  pyenv \
  tmuxp \
  watch \
  asdf \
  heroku

