#!/usr/bin/env bash

# General
brew install --cask brave-browser
brew install --cask rectangle
brew install --cask flux
brew install --cask flycut

# Office Tools
brew install --cask joplin
brew install --cask syncthing
# brew install --cask mailspring
# brew install --cask libreoffice

# Dev Tools
brew install --cask docker
brew install --cask iterm2
brew install --cask sublime-text
brew install --cask fork
brew install --cask postman
# brew install --cask intellij-idea-ce
# brew install --cask tunnelblick
# brew install --cask yed

# Secrets
brew install --cask keepassxc

