#!/usr/bin/env bash

brew tap immortaleeb/tap

brew install coreutils
brew install tmux
brew install ag
brew install gradle
brew install lnav
brew install bashmarks
brew install awscli
brew install jq
brew install docker-compose

