#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Install homebrew
echo "# Installing homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install tools
echo "# Install tools..."
${SCRIPT_DIR}/install-tools

# Install apps
echo "# Install applications..."
${SCRIPT_DIR}/install-apps

# Configuration
echo "# Configuration..."
echo "## MacOS Dock"
${SCRIPT_DIR}/customize-dock

# Manual stuff
cat ${SCRIPT_DIR}/TODO_MANUAL.md
