#!/usr/bin/env bash

# Install homebrew
echo "# Installing homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install tools
echo "# Install tools..."
./install-tools

# Install apps
echo "# Install applications..."
./install-apps

# Configuration
echo "# Configuration..."
echo "## MacOS Dock"
./customize-dock

# Manual stuff
cat ./TODO_MANUAL.md
