#!/usr/bin/env bash

APPLICATIONS_DIR=~/Applications
mkdir -p "${APPLICATIONS_DIR}"

generate_app_image_desktop_file() {
  app_name="$1"
  app_version="$2"
  app_image_path="$3"

  cat > "$HOME/.local/share/applications/${app_name}.desktop" <<EOD
[Desktop Entry]
Name=${app_name}
Exec=${app_image_path} %u
Terminal=false
Type=Application
StartupWMClass=${app_name}
X-AppImage-Version=${app_version}
Comment=${app_name}
EOD
}

download_app_image() {
  app_name="$1"
  app_version="$2"
  app_image="${app_name}-${app_version}.AppImage"
  app_url="$3"

  if [ ! -f "${APPLICATIONS_DIR}/${app_image}" ]; then
    curl -L -o "${APPLICATIONS_DIR}/${app_image}" "$app_url"
    chmod +x "${APPLICATIONS_DIR}/${app_image}"
    generate_app_image_desktop_file "${app_name}" "${app_version}" "${APPLICATIONS_DIR}/${app_image}"
  fi
}

# General
sudo apt-get install -y \
  flameshot

# Office tools
OBSIDIAN_VERSION="1.3.5"
download_app_image "Obsidian" "${OBSIDIAN_VERSION}" "https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_VERSION}/Obsidian-${OBSIDIAN_VERSION}.AppImage"

sudo apt-get install -y \
  syncthing

# Dev tools
sudo apt-get install -y \
  meld

## jetbrains toolbox
if [ ! -d /opt/jetbrains ]; then
  workdir=$(mktemp -d)
  curl -o $workdir/jetbrains-toolbox.tar.gz 'https://download-cdn.jetbrains.com/toolbox/jetbrains-toolbox-1.28.1.15219.tar.gz'
  pushd /opt
  sudo tar -xvzf $workdir/jetbrains-toolbox.tar.gz
  sudo mv jetbrains-toolbox* jetbrains
  popd
fi

# Secrets
sudo apt-get install -y \
  keepassxc

# Multimedia
sudo apt-get install -y \
  vlc

