#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

"${SCRIPT_DIR}/install-tools"

# Set default shell
chsh -s /bin/zsh $USER

# docker config
sudo groupadd docker
sudo usermod -aG docker $USER


"${SCRIPT_DIR}/customize-desktop"
"${SCRIPT_DIR}/install-apps"

