source "${ZDOTDIR}/zsh-functions"

# homebrew tab completion
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

# tab completion
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
_comp_options+=(globdots) # include hidden files
compinit

# fix shortcuts in tmux
bindkey -e

zsh_add_file "zsh-prompt"
# zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-bashmarks"
zsh_add_file "zsh-nvm"
zsh_add_file "zsh-pyenv"
zsh_add_file "zsh-private"

zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
# zsh_add_completion "zsh-users/zsh-completions"

# load bashmarks
source_file "/usr/local/opt/bashmarks/libexec/bashmarks.sh"
source_file "/usr/share/bashmarks/bashmarks.sh"
source_file "/usr/local/opt/asdf/libexec/asdf.sh"

# load secrets
load_env_file ".secrets.env"

